gateway:
   ip: 192.168.1.186
   
token:
   # 10 days
   expiration_time: 86400000
   secret: heyN0w61984

spring:
  rabbitmq:
     host: localhost
#     port: 15672
     port: 5672
     username: guest
     password: guest
