gateway:
   ip: 192.168.1.186
   
token:
   # 10 days
   expiration_time: 86400000
   secret: heyN0w61984

spring:
  rabbitmq:
     host: localhost
#     port: 15672
     port: 5672
     username: guest
     password: guest
  
  datasource:
     url: jdbc:mysql://localhost:3306/sergey_tutorial_user_service
     username: root
     password: '{cipher}bd026b50a68902273e08d71460acfcebbca163fc05c0ad7c9646350233e8ee9a'
