gateway:
   ip: 192.168.1.186
   
token:
   # 10 days
   expiration_time: 86400000
   secret: heyN0w61984

spring:
  rabbitmq:
     host: localhost
#     port: 15672
     port: 5672
     username: guest
     password: guest
  
  datasource:
     url: jdbc:mysql://localhost:3306/sergey_tutorial_user_service
     username: root
     password: '{cipher}172728bb7ad51af6c1069be9b82416a473a1760a0db44ee033ab0f4c52bf8a18'
